### ISSUE TITLE
App is preventing computer to sleep

### ISSUE THREAD

**Issue by poisutekinshi** [AliceLR/megazeux#367]
On MACOS Silicon, the app prevents the computer to sleep for no reason.
Since this is a security problem (as well as a battery drain) I would like this "feature/bug" to be OFF or an option to turn it off.
In the activity monitor the application details clearly that it prevents the sleep features.

**Comment by AliceLR** [comment]
I think at some point SDL made it default behavior to disable the screensaver and I haven't fixed it yet.

Cross linking DMZX issue: https://www.digitalmzx.com/forums/index.php?app=tracker&showissue=824
