### ISSUE TITLE
[LINUX MINT]Should we also support Mint?!?

### ISSUE THREAD

**Issue by TheRealHamtaro126** [AliceLR/megazeux#491]
I now switched to Mint, and have enough of a reason to try MZX, but there is Ubuntu, Debian, and a lack of "Mint", to say, for a better term for an obvious and unknown reason.

Can someone do something about this situation? If done right and well: Ye shall be praised thy name with honour and glory!

Good luck!!!

**Comment by asiekierka** [comment]
Linux Mint is derived from Ubuntu, so the Ubuntu .deb files should work fine. Unless there's a known issue?

**Comment by TheRealHamtaro126** [comment]
Take a few minutes...

**Comment by AliceLR** [comment]
This doesn't apply to the most recent release since 24.04 was the LTS, but in the future: if the regular Ubuntu uploads don't work (they may rely on a newer glibc), Dizzy usually provides separate stable and LTS .debs [here](https://www.digitalmzx.com/forums/index.php?showtopic=15779).

**Comment by TheRealHamtaro126** [comment]
I downloaded, Ran a Ubuntu Dependancy Package thingy (expected), Then wanted my password, and during half of typing it in for safety, it crashed with a dialog "unexpected handler"!

**Comment by AliceLR** [comment]
> I downloaded, Ran a Ubuntu Dependancy Package thingy (expected), Then wanted my password, and during half of typing it in for safety, it crashed with a dialog "unexpected handler"!

That's unusual. I would try again and/or try updating your system packages (if they are out of date).

If you aren't able to install the MegaZeux .deb from the desktop, you can try installing it from the terminal:
```sh
sudo dpkg --install megazeux_2.93b-1ubuntu1_amd64.deb
```

**Comment by TheRealHamtaro126** [comment]
Done on Command, Nothing appeared yet, I did everything I can... =<

This stinks, Oh well, There is always Zeta and Weave by Wil, KKarios and the gang!!!

Might think about joining MGG at this point ^_^'

**Comment by TheRealHamtaro126** [comment]
Closed until something can be done, But do not count this as a fail or a bust!!!

**Comment by AliceLR** [comment]
What version of Linux Mint are you using?

**Comment by TheRealHamtaro126** [comment]
> What version of Linux Mint are you using?
> 

The latest, as of the speaking here...

> As another aside: neither of those have Linux Mint packages.

Weave or plain ZZT/SZT is supported with ZETA, Downloaded on Aise's Page or on Github!!!

**Comment by TheRealHamtaro126** [comment]
And already I found it on the GAMES section, Should look when installing next time...
